#@api_HostAddress = http://localhost:5137

@api_HostAddress = https://finshark-gfhvfzgpd6gvgngf.canadacentral-01.azurewebsites.net/

GET {{api_HostAddress}}/weatherforecast/
Accept: application/json

###
